name: evaluation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9  
  - pillow
  - pynfft
  - pip
  - pip:
    - ehtim==1.2.4
    - numpy==1.21.1
    - scipy==1.10.1
    - pandas==1.5.3
    - scikit-image
    - networkx
    - matplotlib
    - h5py
    - astropy
    - pyyaml
    - tqdm
    - git+https://github.com/liamedeiros/ehtplot.git
